---
collections:
  - name: ansible.netcommon
    version: ">=2.0.0"
  - name: f5networks.f5_modules
  - name: f5networks.f5_bigip
  - name: ansible.posix
  - name: community.docker
  - name: community.general
