---
collections:
  - ansible.utils
  - community.general
  - redhat.rhel_system_roles
  - redhat.insights
roles:
  - linux-system-roles.firewall
  - redhatinsights.insights-client
  - dev-sec.ssh-hardening
  - redhatofficial.rhel8_pci_dss
