# Workflow name
name: f5-test-ee

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'f5-test-ee/**'

  # Schedule workflow run at 00:00 on Sunday
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-deploy-workflow:
    uses:  VDI-Tech-Guy/f5-execution-engines/.github/workflows/deploy.yml@main
    with:
      EE_FOLDER_NAME: 'f5-test-ee'
      EE_IMAGE_TAG: 'latest'
      QUAY_USER: 'f5_business_development'
    secrets:
      REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
      REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
